/*
 * This software Copyright by the RPTools.net development team, and
 * licensed under the Affero GPL Version 3 or, at your option, any later
 * version.
 *
 * RPTools Source Code is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You should have received a copy of the GNU Affero General Public
 * License * along with this source Code.  If not, please visit
 * <http://www.gnu.org/licenses/> and specifically the Affero license
 * text at <http://www.gnu.org/licenses/agpl.html>.
 */
package net.rptools.mtscript.util;

/** Interface for classes that provide constants used through out the parser and execution. */
public interface MTScriptConstants {

  /**
   * Returns a prefix that can be used for internal symbols that is guaranteed not to be the start
   * of any symbol generated by parsing.
   *
   * @return a prefix that can be used for internal symbols.
   */
  String getInternalSymbolPrefix();

  /**
   * The name of the symbol in the {@link net.rptools.mtscript.symboltable.SymbolTable} that holds
   * the script entry point.
   *
   * @return The name of the symbol in the {@link net.rptools.mtscript.symboltable.SymbolTable} that
   *     hold the script entry point.
   */
  String getEntryPointSymbolName();
}
